apiVersion: v2
name: prometheus-stack
description: Wrapper chart for kube-prometheus-stack (Prometheus + Grafana)
type: application
version: 0.1.0
appVersion: "0.70.0"

dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
