apiVersion: v2
name: ingress-nginx
description: Wrapper chart for ingress-nginx controller
type: application
version: 0.1.0
appVersion: "1.9.5"

dependencies:
  - name: ingress-nginx
    version: "4.9.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
