apiVersion: v2
name: cilium
description: Wrapper chart for Cilium CNI
type: application
version: 0.1.0
appVersion: "1.14.5"

dependencies:
  - name: cilium
    version: "1.14.5"
    repository: "https://helm.cilium.io/"
